### ISSUE TITLE
future::plan() - please undo afterward

### ISSUE THREAD

**Issue by HenrikBengtsson** [dipterix/dipsaus#4]
Hi.  I noticed that you set `plan()` in your package:

https://github.com/dipterix/dipsaus/blob/7bff91819d4ddf8ad234abce69804696a832521d/R/parallels-future.R#L56-L58

Please make sure to undo these changes upon exiting the function.

From ?future::plan:

> # For package developers
> 
> Please refrain from modifying the future strategy inside your packages / functions, i.e. do not call `plan()` in your code. Instead, leave the control on what backend to use to the end user. This idea is part of the core philosophy of the future framework - as a developer you can never know what future backends the user have access to. Moreover, by not making any assumptions about what backends are available, your code will also work automatically with any new backends developed after you wrote your code.
> 
> If you think it is necessary to modify the future strategy within a function, then make sure to undo the changes when exiting the function. This can be done using:
> 
> ```r
>   oplan <- plan(new_set_of_strategies)
>   on.exit(plan(oplan), add = TRUE)
>   [...]
> ```
> 
> This is important because the end-user might have already set the future strategy elsewhere for other purposes and will most likely not known that calling your function will break their setup. Remember, your package and its functions might be used in a greater context where multiple packages and functions are involved and those might also rely on the future framework, so it is important to avoid stepping on others' toes. 

Thxs

**Comment by dipterix** [comment]
@HenrikBengtsson Thanks for pointing out. Here's the fix.

https://github.com/dipterix/dipsaus/blob/8ed8a87de61e04f174d785e73afb1a837502b584/R/parallels-future.R#L61-L64

https://github.com/dipterix/dipsaus/blob/8ed8a87de61e04f174d785e73afb1a837502b584/R/parallels.R#L230-L240

**Comment by dipterix** [comment]
The new version has been on CRAN now. Closing this issue.
