### ISSUE TITLE
cannot follow async evaluator vignette

### ISSUE THREAD

**Issue by copernican** [dipterix/dipsaus#5]
I'm trying to follow along with the Asynchronous Evaluator vignette, but am getting the below error. I installed dipsaus 0.1.1 from CRAN with `dependencies = TRUE`. Any idea what might be going on?

``` r
library(dipsaus)
evaluator <- make_async_evaluator(name = 'test', n_nodes = 1, n_subnodes = 1)
#> Error in qs_queue(file.path(private$path, "Q0")): could not find function "qs_queue"
```

<sup>Created on 2021-01-06 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by dipterix** [comment]
Sorry @copernican `make_async_evaluator` is to be deprecated. It only exists for some compatibility issues. Would you mind describe what kind of features you are looking for? I might be able to find you some alternatives.

**Comment by copernican** [comment]
Understood about `make_async_evaluator()` being deprecated, and thanks for the offer. I ended up going with a different solution.
