### ISSUE TITLE
default color for compoundInput2 follows palette()

### ISSUE THREAD

**Issue by jmagnotti** [dipterix/dipsaus#9]
I think the default label_color for compoundInput2 should grab the value of par('fg') or par('col.lab') or similar rather than the value from palette(). This would align the behavior of the function to base R and make it possible to make sweeping changes to the UI via a call to par(). And it also allows people to use the default value without fear of ending up with orange labels because of a previous call to palette()

thanks for considering!

**Comment by dipterix** [comment]
Thanks @jmagnotti this issue has been fixed and the update will be included in the next release.
